### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by axelSok** [robrich/gulp-exec#27]
Hi!
I use galp-exec  to generate the report for tests. But when the number of tests has increased , the report no longer fit into the buffer (200kb) and i receive "stdout maxBuffer exceeded". 
How can i manage child_process-buffer from gulp-exec?
Thanks

**Comment by alex-chuev** [comment]
+1

**Comment by robrich** [comment]
Sounds like you've outgrown this plugin, and should use through2 and child_process directly.  You may also find success in moving from `child_process.exec()` to `child_process.spawn()` since spawn doesn't buffer output.  See https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

**Comment by kervinpierre** [comment]
This should be noted on the plugin page to save others the trouble of finding that out.

**Comment by robrich** [comment]
Good idea.  Want to prepare a PR for the readme.md?

**Comment by mmc41** [comment]
I have the same issue - could the buffersize not simply be an option in order to avoid this ?

**Comment by robrich** [comment]
Generally when your output gets this big, you'd rather use child-process.spawn rather than .exec, so you've likely outgrown gulp-exec.  A PR for buffersize sounds like a good move.  Is this not one of the options passed directly to exec?
